/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import makanan.buburr;

/**
 *
 * @author user
 */
public class framebubur extends javax.swing.JFrame {

    /**
     * Creates new form framebubur
     */
    public framebubur() {
        initComponents();
        reset();
    }
    
    void reset(){
        tbumbu.setText(null);
        trasa.setText(null);
        ttekstur.setText(null);
        ttoping.setText(null);
        twarna.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbumbu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrasa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtekstur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jwarna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtoping = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        trasa = new javax.swing.JLabel();
        tbumbu = new javax.swing.JLabel();
        ttekstur = new javax.swing.JLabel();
        twarna = new javax.swing.JLabel();
        ttoping = new javax.swing.JLabel();
        ttampil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("bubur");

        jLabel2.setText("Rasa");

        jbumbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbumbuActionPerformed(evt);
            }
        });

        jLabel3.setText("bumbu");

        jrasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrasaActionPerformed(evt);
            }
        });

        jLabel4.setText("tekstur");

        jtekstur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteksturActionPerformed(evt);
            }
        });

        jLabel5.setText("warna");

        jwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwarnaActionPerformed(evt);
            }
        });

        jLabel6.setText("toping");

        jtoping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtopingActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        trasa.setText("rasa:");

        tbumbu.setText("bumbu:");

        ttekstur.setText("tekstur:");

        twarna.setText("warna:");

        ttoping.setText("toping:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttoping)
                    .addComponent(twarna)
                    .addComponent(ttekstur)
                    .addComponent(tbumbu)
                    .addComponent(trasa))
                .addGap(0, 153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trasa)
                .addGap(28, 28, 28)
                .addComponent(tbumbu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(ttekstur)
                .addGap(37, 37, 37)
                .addComponent(twarna)
                .addGap(38, 38, 38)
                .addComponent(ttoping)
                .addGap(30, 30, 30))
        );

        ttampil.setText("tampil");
        ttampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtekstur, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jwarna, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtoping, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jrasa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jbumbu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jrasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbumbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtekstur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtoping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ttampil)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbumbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbumbuActionPerformed
    



    }//GEN-LAST:event_jbumbuActionPerformed

    private void jteksturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteksturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jteksturActionPerformed

    private void jwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jwarnaActionPerformed

    private void jtopingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtopingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtopingActionPerformed

    private void jrasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrasaActionPerformed

    private void ttampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttampilActionPerformed
     buburr bubur = new buburr();
bubur.setRasa(jrasa.getText());
bubur.setBumbu (jbumbu.getText());
bubur.setTekstur (jtekstur.getText());
bubur.setWarna (jwarna.getText());
bubur.setTopping (jtoping.getText());

trasa.setText("rasa \t:"+ bubur.getRasa());
tbumbu.setText("bumbu \t:" + bubur.getBumbu());
ttekstur.setText("tekstur \t:" + bubur.getTekstur());
twarna.setText("warna \t: " + bubur.getWarna());
ttoping.setText("toping \t:" + bubur.getTopping());
    }//GEN-LAST:event_ttampilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framebubur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framebubur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framebubur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framebubur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framebubur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jbumbu;
    private javax.swing.JTextField jrasa;
    private javax.swing.JTextField jtekstur;
    private javax.swing.JTextField jtoping;
    private javax.swing.JTextField jwarna;
    private javax.swing.JLabel tbumbu;
    private javax.swing.JLabel trasa;
    private javax.swing.JButton ttampil;
    private javax.swing.JLabel ttekstur;
    private javax.swing.JLabel ttoping;
    private javax.swing.JLabel twarna;
    // End of variables declaration//GEN-END:variables
}
